# Generated by Django 4.1.3 on 2023-02-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ichimlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom1', models.CharField(max_length=31)),
                ('rasm1', models.CharField(max_length=255)),
                ('admin1', models.CharField(max_length=31)),
                ('sana1', models.DateTimeField(auto_now_add=True)),
                ('nom2', models.CharField(max_length=31)),
                ('rasm2', models.CharField(max_length=255)),
                ('admin2', models.CharField(max_length=31)),
                ('sana2', models.DateTimeField(auto_now_add=True)),
                ('nom3', models.CharField(max_length=31)),
                ('rasm3', models.CharField(max_length=255)),
                ('admin3', models.CharField(max_length=31)),
                ('sana3', models.DateTimeField(auto_now_add=True)),
                ('nom4', models.CharField(max_length=31)),
                ('rasm4', models.CharField(max_length=255)),
                ('admin4', models.CharField(max_length=31)),
                ('sana4', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
